# Generated by Django 5.1.1 on 2024-09-30 08:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencarpark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='exit_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
