# Generated by Django 5.1.1 on 2024-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencarpark', '0002_alter_parkinghistory_exit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
