# Generated by Django 5.1.1 on 2024-09-30 14:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencarpark', '0003_alter_parkinghistory_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='entry_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
