# Generated by Django 5.1.1 on 2024-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencarpark', '0004_alter_parkinghistory_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
