# Generated by Django 5.1.1 on 2026-08-24 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencarpark', '0005_alter_parkinghistory_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinghistory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_spot', to='greencarpark.parkingspot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('disable', 'Disable'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_vehicle', to='greencarpark.vehicle'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='parking_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_history', to='greencarpark.parkinghistory'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('wait', 'Wait'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='wait', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_booking', to='greencarpark.booking'),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='entry_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='exit_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_spot', to='greencarpark.parkingspot'),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_sub', to='greencarpark.subscription'),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_vehicle', to='greencarpark.vehicle'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('in_use', 'In Use'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_booking', to='greencarpark.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_sub', to='greencarpark.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_spot', to='greencarpark.parkingspot'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('cancel', 'Cancel'), ('expired', 'Expired')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_type', to='greencarpark.subscriptiontype'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status', 'start_time'], name='idx_bk_usr_stat_time'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['spot', 'status', 'start_time', 'end_time'], name='idx_bk_spot_stat_time'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle', 'status'], name='idx_bk_veh_stat'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', 'status'], name='idx_comp_usr_stat'),
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['user', 'exit_time'], name='idx_hist_user_exit'),
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['vehicle', 'exit_time'], name='idx_hist_veh_exit'),
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['spot', 'exit_time'], name='idx_hist_spot_exit'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['parkinglot', 'status'], name='idx_spot_lot_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', 'created_date'], name='idx_pay_stat_created'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['parkinglot', 'rate'], name='idx_rev_lot_rate'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'end_date'], name='idx_sub_user_stat_date'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['spot', 'status'], name='idx_sub_spot_status'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'license_plate'], name='idx_veh_user_plate'),
        ),
        migrations.AddConstraint(
            model_name='parkinghistory',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('vehicle',), name='unique_active_parking_per_vehicle'),
        ),
    ]
